### ISSUE TITLE
reserved identifier violation

### ISSUE THREAD

**Issue by elfring** [Karbo123/AnalyticMesh#2]
I would like to point out that identifiers like “[`__MLP_H__`](https://github.com/Gorilla-Lab-SCUT/AnalyticMesh/blob/57a2eb675b5b4ca471a0b027dcaa768f414c2efe/backend/inc/mlp.h#L2 "Update candidate")” and “[`__POLYMESH_H__`](https://github.com/Gorilla-Lab-SCUT/AnalyticMesh/blob/57a2eb675b5b4ca471a0b027dcaa768f414c2efe/backend/inc/polymesh.h#L1 "Another update candidate")” [do not fit](https://wiki.sei.cmu.edu/confluence/display/cplusplus/DCL51-CPP.+Do+not+declare+or+define+a+reserved+identifier#DCL51CPP.Donotdeclareordefineareservedidentifier-NoncompliantCodeExample%28HeaderGuard%29 "Do not declare an identifier which is reserved for the compiler implementation.") to the expected naming convention of the C++ language standard.
Would you like to adjust your selection for unique names?

**Comment by Karbo123** [comment]
Oh, thanks for pointing out, but I think you can definitely change the code accordingly on your own if the compilation fails.

Any way, I am happy to merge your commit if you are willing to make a [request](https://github.com/Gorilla-Lab-SCUT/AnalyticMesh/pulls) for this fix.

**Comment by elfring** [comment]
💭 How do you think about to avoid that this software [depends on undefined behaviour](https://www.securecoding.cert.org/confluence/display/c/CC.+Undefined+Behavior#CC.UndefinedBehavior-ub_106 "Avoiding undefined behaviour?")?

**Comment by Karbo123** [comment]
I don't know what exact issue you now have.  For me, the compilation has no problem, and the code works well.

Maybe you can change `__MLP_H__` to `MLP_H` to use a better naming convention?
