### ISSUE TITLE
Remove unnecessary null pointer checks

### ISSUE THREAD

**Issue by elfring** [Karbo123/AnalyticMesh#3]
[An extra null pointer check is not needed in functions](https://isocpp.org/wiki/faq/freestore-mgmt#delete-handles-null "Do I need to check for null before delete p?") like the following.
- [`MLP<FloatType>::init`](https://github.com/Gorilla-Lab-SCUT/AnalyticMesh/blob/57a2eb675b5b4ca471a0b027dcaa768f414c2efe/backend/inc/mlp.h#L62 "MLP<FloatType>::init function")
- [`PolyMesh<FloatType, VERT_MAX>::init`](https://github.com/Gorilla-Lab-SCUT/AnalyticMesh/blob/57a2eb675b5b4ca471a0b027dcaa768f414c2efe/backend/inc/polymesh.h#L66 "PolyMesh<FloatType, VERT_MAX>::init function")

**Comment by Karbo123** [comment]
Thanks for this. Checking if it is a nullptr just make me feel better. You can certainly delete the if statement, and it will make the code look better.

You can make a request for code improvement (and with necessary description), and I will be happy to merge your code.
